import os
import time
########C O D E X#######»
os.system("clear")
time.sleep(2)
print("\033[31mM A L W A R E S P Y\033[32mP A G E\033[33m I N \033[31mFacebook")
 
print("")
time.sleep(1)
print("\033[39mFollow Me In Facebook ✓")
print("")
print("\033[36mhttp://shorturl.at/chyY3")
print("")
time.sleep(1)
print("Wait 30 Seconds To Install apt")
print("\033[1;31m Creaded By Malware Spy")
time.sleep(1)
print("\033[1;37m Mokhtar Abdelkreem")
time.sleep(1)
os.system("apt update && apt upgrade -y")
os.system("apt install python -y")
os.system("apt install python2 -y")
os.system("apt install git -y")
os.system("apt install curl -y")
os.system("apt install nano -y")
os.system("apt install perl")
os.system("apt install ruby")
os.system("pip install requests -y")
os.system("pip2 install requests -y")
os.system("apt install unzip -y")
os.system("apt install zip -y")
os.system("apt install wget -y")
os.system("apt install tsu")
os.system("apt install cmatrix")
os.system("apt install php -y")
os.system("apt install nmap -y")
os.system("apt install clang -y")
os.system(" apt install hydra -y")
os.system("apt install tar")
os.system("apt install proot -y")
os.system("apt install toilet -y")
os.system("apt install openssh -y")
os.system("apt install openssl -y")
os.system("termux-setup-storage")
os.system("pip install mechanize")
os.system("pip2 install mechanize")
os.system("pip install -- update")
os.system("pip2 install -- update")

##########
print(" \033[33mUpdating Is Finshed >> Thanks To Use Malware-Spy Script ✓ ")
